My report mention
kurumadaisuke/fjord-books_app-2023 pull request #6
Opened 2023-07-12 12:18 UTC by kurumadaisuke

ご確認よろしくお願いしますmm

2023-07-18 20:36 UTC, komagata commented on app/models/relationship.rb
> +class Relationship < ApplicationRecord
Relationshipですと関連という意味になるのであらゆるテーブル同士の関連が当てはまってしまいます。
ですので、もっと具体的な名前にしたほうが良いかと思います。

2023-08-02 02:40 UTC, komagata commented on db/migrate/20230706063343_create_relationships.rb
> +      t.references :mention, foreign_key: { to_table: :reports }
すでに上の行でreports.idにforeign_keyが作られていますが、こちらの5行目は何のためにある感じでしょうか？

2023-08-09 11:42 UTC, kurumadaisuke commented on db/migrate/20230706063343_create_relationships.rb
> +      t.references :mention, foreign_key: { to_table: :reports }
4行目で外部キー設定していたので、5行目の外部キーの設定は不要でした🙏
修正したものをコミットしました🙏

2023-08-09 12:50 UTC, komagata commented on config/routes.rb
> +  resources :relationships
こちらは何に使っていますか？

2023-08-09 12:50 UTC, komagata commented on app/controllers/report_mentions_controller.rb
> +# frozen_string_literal: true
こちらは使われていますでしょうか？

2023-08-09 12:50 UTC, komagata commented on app/models/report.rb
> +  has_many :reverse_of_relationships, class_name: 'ReportMention', foreign_key: 'mention_id', dependent: :destroy, inverse_of: :mention
関連の逆という名前ですと、全てテーブル通しのつながりは「関連」になりますし、それの逆は「関連の逆」になるので同じ状態のデータがすぐに出てきてしまいそうです。
別の具体的な名前にした方がいいと思います。

2023-08-10 01:29 UTC, kurumadaisuke commented on app/controllers/report_mentions_controller.rb
> +# frozen_string_literal: true
rubocopを使ったらエラーが発生し、ファイルの一番上に「#frozen_string_literal: true」を入れることが推進されるため、コードに含んでおりました！
正直、なぜこのコードを導入しないといけないのかは理解不足なところがありrubocopで怒られるから入れておりました🙏
現状の私の理解として、
「文字列を文字列として扱うために凍結(変更させない)ために使用するもの」っと理解しておりますmm
これはRubyが動的型付け言語だから？など勝手に想像していました🙏

以下、参考記事
https://qiita.com/YutoYasunaga/items/98111ef50927ecb4135d

2023-08-10 11:40 UTC, kurumadaisuke commented on config/routes.rb
> +  resources :relationships
relationに対して作成や削除などあったので、コードに記述していましたがそもそも不要だったので削除しました🙏
削除しても動作することを確認しました！

2023-08-13 21:17 UTC, komagata commented on app/controllers/report_mentions_controller.rb
> +# frozen_string_literal: true
すみません、僕の書き方がわかりづらかったですよね。

`ReportMentionsController`というクラス、このファイル自体このアプリで使われていますかね？
使われていないように見えたので。

2023-08-13 21:17 UTC, komagata commented on app/models/report.rb
> +  has_many :mentioned_reports_relationships, class_name: 'ReportMention', foreign_key: 'mention_id', dependent: :destroy, inverse_of: :mention
DBのテーブル同士のつながりは全て関連と言えるのでrelationshipという単語自体意味の重複になってしまい、結果無意味な情報になるので単語自体使わない方がいいかもです。

2023-08-13 23:49 UTC, kurumadaisuke commented on app/controllers/report_mentions_controller.rb
> +# frozen_string_literal: true
確かに使っていないかったので不要なファイルなので削除いたしましたmm

2023-08-15 18:43 UTC, komagata requested changes

2023-08-15 18:43 UTC, komagata commented on app/controllers/reports_controller.rb
> +      mention_reports_create
reportsの保存とreport_mentionsの保存が別々になっているのでreport_mentionsの保存に失敗した場合に、reportsだけが保存されてしまうという問題があると思います。

updateにも同じ問題があるのでtransactionをキーワードに調べてみるとわかるかと思います〜。

2023-08-20 03:43 UTC, komagata requested changes

2023-08-20 03:43 UTC, komagata commented on app/controllers/reports_controller.rb
> +    if @report.save!
トランザクションについて、何故存在するのか、どういった機能なのかもう少し調べてみてください。

現状ですと、reportの保存に成功して、report_mentionの保存に失敗した場合、reportだけ保存された状態になってデータの不整合が起きてしまいます。

この問題を解決するためにActiveRecordのトランザクション機能を使ってみてください。

2023-08-21 10:54 UTC, kurumadaisuke commented on app/controllers/reports_controller.rb
> +    if @report.save!
トランザクションについてこちらの記事を参考にしました!!
https://qiita.com/mtoyopet/items/67d1cff3df00aa651cb7

2023-08-26 04:17 UTC, komagata commented on app/models/report.rb
> +      return unless content.include?('http://localhost:3000')
transactionに不要な処理がたくさん入っているので、必要な部分だけをtransactionで囲って見てください〜。

2023-08-28 08:33 UTC, komagata commented on app/models/report.rb
> +  # after_update :mention_reports_update
gitでバージョン管理されていて、いつでも元の状態に戻せるので、不要なコメントは削除しちゃったほうがいいと思います。

2023-08-28 08:33 UTC, komagata commented on app/models/report.rb
> +  def self.create_report_with_mentions(user, report_params)
reportに関することなのでインスタンスメソッドにした方がスマートになると思います。

2023-08-28 08:33 UTC, komagata commented on app/models/report.rb
> +      raise ActiveRecord::Rollback unless report.save!
最小限のサンプルを作って試してみるとわかると思いますが、手動でエラーを起こさなくても保存時にエラーが発生すれば自動的にロールバックされるかと思います。

2023-08-28 23:42 UTC, kurumadaisuke commented on app/models/report.rb
> +  # after_update :mention_reports_update
失礼しました！
削除するの抜けていました🙏

2023-08-29 09:18 UTC, kurumadaisuke commented on app/models/report.rb
> +      raise ActiveRecord::Rollback unless report.save!
手動でエラーを起こさなくとも、以下コミットした時のコードだった際は自動的にロールバックすることを確認できました🙏
今回、私が無駄なコード書き足したので本来は以下コミット履歴のコードにする方が良かったのでしょうか🙏？
https://github.com/kurumadaisuke/fjord-books_app-2023/pull/6/commits/1888d2a5c5f783a444b12ffa3262934a532c0afa

2023-08-30 12:32 UTC, komagata commented on app/models/report.rb
> +      raise ActiveRecord::Rollback unless report.save!
@kurumadaisuke 

> 今回、私が無駄なコード書き足したので本来は以下コミット履歴のコードにする方が良かったのでしょうか🙏？

回答としてはどちらも間違っているのでNOになります。

今回のコードについて、繰り返しになりますが、`raise ActiveRecord::Rollback`のように手動でエラーを起こす必要はありません。

前回のコードについては、トランザクションについての基本的なところが間違って理解されているかもです。

ReportとReportMentionの保存で、エラー時の不整合を防ぐためにトランザクションを使うので、大雑把に書くと下記のように二つの保存をトランザクションで囲んでないと意味がないです。

```ruby
transaction do
  Report.create
  ReportMention.create
end
```

updateに関しても同様なので確認してみてください。

2023-09-04 11:37 UTC, komagata commented on app/models/report.rb
> +    ReportMention.transaction do
```ruby
Report.transaction do
  ReportMention.transaction do
    # ...
  end
end
```

このように不必要にtransactionが入れ子になっているようです。外側だけで大丈夫です。

2023-09-07 15:29 UTC, komagata commented on app/models/report.rb
> +    Report.transaction do
```suggestion
   transaction do
```

これで良いかもです。

2023-09-07 15:29 UTC, komagata commented on app/models/report.rb
> +  end
メンションがない時にcreate_mentionsが動いても問題ないように作られていれば（もしかしたら現状でも大丈夫かも？）、下記のようにかけてスマートでわかりやすいかもです。

```suggestion
  def create_with_mentions
   transaction do
      save && create_mentions
    end
  end
```

贅沢を言えば、create_mentions, update_mensionsをsave_mentionsと言う名前で共通化できたら

`save && save_mentions`と書けるのでより読む人にとって理解しやすいかもです〜。

2023-09-08 01:45 UTC, kurumadaisuke commented on app/models/report.rb
> +  end
なるほどです！！こういった書きかたがあるんですね！！
勉強になります🙇‍♂️

2023-09-09 09:33 UTC, komagata commented on app/models/report.rb
> +  end
@kurumadaisuke ちょっと僕は動かしていないので実際に下記の場合に問題なく動くのかわかってないのですが大丈夫な感じでしょうか？

> メンションがない時にcreate_mentionsが動いても問題ないように作られていれば

2023-09-09 12:48 UTC, kurumadaisuke commented on app/models/report.rb
> +  end
このところが動作確認を行った結果問題ありませんでした🙏
メンションがない日報作成の場合、ReportMention.allの結果は以下のようになっておりました🙏
```
irb(main):001:0> ReportMention.all
  ReportMention Load (0.6ms)  SELECT "report_mentions".* FROM "report_mentions"
=> [] 
```

2023-09-11 09:01 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2023-09-11 11:18 UTC, merged